### ISSUE TITLE
未找到入口 app.json 文件

### ISSUE THREAD

**Issue by LWD8** [mini-mpvue/mpvue-douban#10]
### 请问一下怎么微信者开发工具打开？
![image](https://user-images.githubusercontent.com/28432674/49557605-25606700-f943-11e8-9e9f-67493a8ac9ba.png)
![image](https://user-images.githubusercontent.com/28432674/49557655-41fc9f00-f943-11e8-8c8b-b6c9c1cdad6d.png)

**Comment by savoygu** [comment]
使用开发者工具打开项目，

<img width="417" alt="wx20181206-123046 2x" src="https://user-images.githubusercontent.com/9302866/49561544-cd316100-f952-11e8-89b7-653d1c1baebb.png">

然后在命令行运行： `npm install && npm run dev:proxy1`

**Comment by LWD8** [comment]
![image](https://user-images.githubusercontent.com/28432674/49564288-f6a3ba00-f95d-11e8-8f93-50ccbe43b73f.png)
好吧，微信开发者打错了，不过你那几个项目打包的结果都是这样的。不知道是不是哪个版本问题还是怎样

**Comment by LWD8** [comment]
问题解决了，需要把package.json文件里mpvue-loader的’^'这个去掉，再npm install即可. 更新详情可以[看这文档](https://segmentfault.com/a/1190000017280556)

**Comment by savoygu** [comment]
解决了就好。
正常来说去掉 ^ 只是安装固定版本的 mpvue-loader，与最新版 mpvue-loader 应该没太大差别。
我通过移除 dist 和 node_modules 目录，重新安装与运行，没遇到你说的问题。
