### ISSUE TITLE
 request:fail invalid url "/coming_soon?start=0&count=3"

### ISSUE THREAD

**Issue by idiot22** [mini-mpvue/mpvue-douban#11]
报这个错，不知道什么问题

**Comment by savoygu** [comment]
应该是本地代理没有启动导致的！运行 `npm run dev:proxy1` 可以解决问题。

运行  `npm run dev:proxy1` 是同时运行 `npm run dev` 和 `npm run proxy1` ，其中 `npm run proxy1` 是启动本地代理访问豆瓣 Api。可以参见文档：[https://github.com/mini-mpvue/mpvue-douban#%E8%BF%90%E8%A1%8C](https://github.com/mini-mpvue/mpvue-douban#%E8%BF%90%E8%A1%8C)
