### ISSUE TITLE
接口返回  invalid_apikey

### ISSUE THREAD

**Issue by xixikou** [mini-mpvue/mpvue-douban#12]
{msg: "invalid_apikey", code: 104, request: "GET /v2/movie/coming_soon"}
code: 104
msg: "invalid_apikey"
request: "GET /v2/movie/coming_soon"

**Comment by savoygu** [comment]
导致原因是：最近豆瓣 Api 做了调整，可以参考：https://github.com/zce/douban-api-proxy
重新获取一下代码，就可以访问了
