### ISSUE TITLE
大神你好

### ISSUE THREAD

**Issue by jilaokang** [mini-mpvue/mpvue-douban#7]
看到很多采用了scss @include a-z('')这样的写法，但是没有找到被incldue根文件，想问一下这个疑惑

**Comment by savoygu** [comment]
https://vue-loader-v14.vuejs.org/zh-cn/configurations/pre-processors.html

![image](https://user-images.githubusercontent.com/9302866/43034339-558ea92a-8d0d-11e8-80dd-bdb2f1964a29.png)

这个项目中是这样配置的：https://github.com/mini-mpvue/mpvue-douban/blob/master/build/utils.js#L68-L79

**Comment by savoygu** [comment]
![image](https://user-images.githubusercontent.com/9302866/43034429-c49be3fe-8d0e-11e8-9429-9cbd7c421569.png)
这样的写法用到的是这个：https://github.com/zgabievi/sass-bem

**Comment by jilaokang** [comment]
好的，非常感谢！

**Comment by javanf** [comment]
`export default {
  config: {
    enablePullDownRefresh: true
  }
}`
您好，为什么我在main.js里面配置了enablePullDownRefresh: true，没有生效了？？？

**Comment by savoygu** [comment]
![image](https://user-images.githubusercontent.com/9302866/44640489-8f887800-a9f4-11e8-88bb-03df75bec4ea.png)
@javanf 如果配置了并且是生效的，会出现上图的效果（支持下拉，并且有loading的效果），这个配置只是触发行为，具体的数据获取动作还是要通过 `onPullDownRefresh` 实现，可以看下 `src/page/list`，里面有相关的例子

**Comment by javanf** [comment]
恩，全局json里面配置是有loading的，但是main.js单个页面配置是没有效果的，list页面有写`onPullDownRefresh`方法，同样没有loading，所以也没有触发。

**Comment by javanf** [comment]
非常感谢，mpvue-loader版本问题，已经解决。
